"use client";

import { useCallback, useState } from "react";
import { useMachineApi, MachineNotice } from "@/components/machine-api";
import { usePoll } from "@/components/hooks";
import {
  Badge,
  Button,
  Card,
  EmptyState,
  ErrorNote,
  PageHeader,
  Stat,
  Toggle,
  useToast,
} from "@/components/ui";

type Artifact = { path: string; name: string; sizeKb: number };
type RepoDisk = { name: string; path: string; sizeKb: number; artifacts: Artifact[] };
type CacheDisk = { label: string; path: string; sizeKb: number };

type Snapshot = {
  enabled: boolean;
  cachedAt: string | null;
  data: { root: string; repos: RepoDisk[]; caches: CacheDisk[]; reclaimableKb: number } | null;
  scanMs?: number;
};

type Vitals = { disk: { freeKb: number; totalKb: number; usedPct: number } | null };

function formatKb(kb: number): string {
  if (kb >= 1024 * 1024) return `${(kb / 1024 / 1024).toFixed(1)} GB`;
  if (kb >= 1024) return `${(kb / 1024).toFixed(0)} MB`;
  return `${kb} KB`;
}

const ROW =
  "card-surface grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-3.5 rounded-xl border border-line px-3.5 py-2.5 transition-colors hover:border-line-bright";

export default function DiskPage() {
  const { apiGet, apiPost, remote, machine, status } = useMachineApi();
  const [snap, setSnap] = useState<Snapshot | null>(null);
  const [disk, setDisk] = useState<Vitals["disk"]>(null);
  const [error, setError] = useState("");
  const [rescanning, setRescanning] = useState(false);
  const [busy, setBusy] = useState<string | null>(null);
  const [enabled, setEnabled] = useState(true);
  const toast = useToast();

  const refresh = useCallback(async () => {
    try {
      setSnap(await apiGet<Snapshot>("/api/disk"));
      setError("");
    } catch (err) {
      setError(`Scanner unavailable: ${(err as Error).message}`);
    }
    apiGet<{ data: Vitals | null }>("/api/vitals")
      .then((v) => setDisk(v.data?.disk ?? null))
      .catch(() => {});
  }, []);

  usePoll(refresh, 5 * 60_000);

  const rescan = useCallback(async () => {
    setRescanning(true);
    try {
      setSnap(await apiGet<Snapshot>("/api/disk?force=1"));
    } catch (err) {
      toast((err as Error).message, true);
    } finally {
      setRescanning(false);
    }
  }, [toast]);

  const clean = useCallback(
    async (target: string, label: string) => {
      if (!window.confirm(`Delete ${target}?\n\n${label} is regenerated by the next build or install.`))
        return;
      setBusy(target);
      try {
        const r = await apiPost<{ freedKb: number }>("/api/disk/clean", { path: target });
        toast(`Freed ${formatKb(r.freedKb)}.`);
        await refresh();
      } catch (err) {
        toast((err as Error).message, true);
      } finally {
        setBusy(null);
      }
    },
    [refresh, toast],
  );

  const toggleModule = useCallback(
    async (next: boolean) => {
      setEnabled(next);
      try {
        await apiPost("/api/settings", { modules: { disk: next } });
        await refresh();
      } catch (err) {
        toast((err as Error).message, true);
        setEnabled(!next);
      }
    },
    [refresh, toast],
  );

  const data = snap?.data;
  const repos = data?.repos.filter((r) => r.artifacts.length) || [];

  return (
    <>
      <PageHeader
        eyebrow="Bilge"
        title="Disk & reclaimable space"
        description="Build artifacts under your dev root and tool caches in your home directory. Everything listed is regenerated on the next install or build; cleaning only ever deletes directories with these exact names."
        right={!remote && <Toggle checked={enabled} onChange={toggleModule} label="Module on" />}
      />
      <div className="mb-4 flex flex-wrap items-center gap-3">
        <Button busy={rescanning} onClick={rescan}>
          {rescanning ? "Measuring…" : "Rescan"}
        </Button>
        <span className="font-mono text-[11px] leading-relaxed text-quiet">
          {data
            ? `${data.repos.length} repos${snap?.scanMs !== undefined ? ` / ${snap.scanMs}ms` : ""}${
                snap?.cachedAt ? ` · ${new Date(snap.cachedAt).toLocaleTimeString()}` : ""
              }`
            : "measuring…"}
        </span>
      </div>
      <ErrorNote message={error} />
      <div data-machine={machine.id}>
        <MachineNotice status={status} />
      </div>
      {snap?.enabled === false ? (
        <EmptyState glyph="[x]" title="Module off" hint="Switch it back on above." />
      ) : !data ? (
        <EmptyState glyph="[…]" title="Measuring your dev root" hint="du over every repo takes a few seconds the first time." />
      ) : (
        <>
          <div className="mb-6 flex flex-wrap gap-x-10 gap-y-4">
            <Stat value={formatKb(data.reclaimableKb)} label="reclaimable" />
            {disk && (
              <Stat
                value={formatKb(disk.freeKb)}
                label={`free of ${formatKb(disk.totalKb)}${disk.usedPct >= 90 ? " · nearly full" : ""}`}
              />
            )}
          </div>
          <div className="flex items-center justify-between px-0.5 mt-6 mb-3 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">
            <span>Repos with artifacts</span>
            <span className="text-quiet tracking-[0.08em]">{repos.length} of {data.repos.length}</span>
          </div>
          {repos.length === 0 ? (
            <EmptyState glyph="[ ✓ ]" title="Nothing to reclaim" hint="No node_modules, build output, or virtualenvs under the dev root." />
          ) : (
            repos.map((repo) => (
              <Card key={`${machine.id}:${repo.path}`} className="p-[22px_24px] mb-3.5">
                <div className="mb-2.5 flex items-baseline justify-between gap-3">
                  <div className="min-w-0">
                    <h3 className="truncate">{repo.name}</h3>
                    <p className="mt-1 truncate font-mono text-[11px] leading-relaxed text-quiet">{repo.path}</p>
                  </div>
                  <span className="flex-none font-mono text-xs text-muted">{formatKb(repo.sizeKb)} total</span>
                </div>
                <div className="flex flex-col gap-1.5">
                  {repo.artifacts.map((a) => (
                    <div key={a.path} className={ROW}>
                      <span className="truncate font-mono text-muted" title={a.path}>
                        {a.name}
                      </span>
                      <Badge variant={a.sizeKb >= 1024 * 1024 ? "alarm" : "quiet"}>{formatKb(a.sizeKb)}</Badge>
                      <Button variant="stop" busy={busy === a.path} onClick={() => void clean(a.path, a.name)}>
                        Clean
                      </Button>
                    </div>
                  ))}
                </div>
              </Card>
            ))
          )}
          <div className="flex items-center justify-between px-0.5 mt-6 mb-3 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">
            <span>Tool caches</span>
            <span className="text-quiet tracking-[0.08em]">{data.caches.length} present</span>
          </div>
          {data.caches.length === 0 ? (
            <p className="font-mono text-[11px] leading-relaxed text-quiet">No known tool caches found.</p>
          ) : (
            <Card className="p-[22px_24px]">
              <div className="flex flex-col gap-1.5">
                {data.caches.map((c) => (
                  <div key={c.path} className={ROW}>
                    <div className="min-w-0">
                      <span className="block truncate font-mono text-muted">{c.label}</span>
                      <span className="block truncate font-mono text-[11px] leading-relaxed text-quiet" title={c.path}>
                        {c.path}
                      </span>
                    </div>
                    <Badge variant={c.sizeKb >= 1024 * 1024 ? "alarm" : "quiet"}>{formatKb(c.sizeKb)}</Badge>
                    <Button variant="stop" busy={busy === c.path} onClick={() => void clean(c.path, c.label)}>
                      Clean
                    </Button>
                  </div>
                ))}
              </div>
            </Card>
          )}
        </>
      )}
    </>
  );
}
